source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'devise'
gem 'omniauth'
gem 'pg'
gem 'omniauth-facebook', :git => 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'omniauth-contrib', :git => 'git://github.com/intridea/omniauth-contrib.git'
gem 'omniauth-weibo', :git => 'git://github.com/ballantyne/omniauth-weibo.git'
gem 'omniauth-douban', :git => 'git://github.com/ballantyne/omniauth-douban.git'
gem 'omniauth-tqq', :git => 'git://github.com/ballantyne/omniauth-tqq.git'
gem 'omniauth-tsohu', :git => 'git://github.com/ballantyne/omniauth-tsohu.git'
gem 'omniauth-t163', :git => 'git://github.com/ballantyne/omniauth-t163.git'
gem 'omniauth-kaixin', :git => 'git://github.com/ballantyne/omniauth-kaixin.git'
gem 'omniauth-renren', :git => 'git://github.com/ballantyne/omniauth-renren.git'
gem 'omniauth-tianji', :git => 'git://github.com/ballantyne/omniauth-tianji.git'
gem 'omniauth-plurk', :git => 'git://github.com/ballantyne/omniauth-plurk.git'
gem 'omniauth-tudou', :git => 'git://github.com/ballantyne/omniauth-tudou.git'
gem 'omniauth-jiepang', :git => 'git://github.com/ballantyne/omniauth-jiepang.git'
gem 'heroku'